### PR TITLE
Add card reader support

### PR DESCRIPTION
**Pull request by willmav5000**
I've added Sinetek-rtsx.kext which is a macOS driver for Realtek SD card readers - https://github.com/sinetek/Sinetek-rtsx.

### CODE REVIEW

**Comment by dfsnc** [comment]
I've tried this driver, it can cause system freeze some times when you using the card reader.

I also tried your branch, it still have the same issue.

**Comment by willmav5000** [comment]
What kind of cards are you using as I've been using this without any issues all day to pull some photos from multiple cards?

**Comment by dfsnc** [comment]
I'm using this.
IMG_5203_fixed

**Comment by willmav5000** [comment]
I've been using full size sd cards but I have one of those somewhere, I'll try it out and let you know how it goes.

**Comment by dfsnc** [comment]
OK, thank you!

**Comment by willmav5000** [comment]
After some further testing I'm only having issues after returning from sleep where the eject button won't always work and sometimes the contents of newly inserted cards isn't detected.

**Comment by dfsnc** [comment]
Well, it's not perfect, but at least it works.

**Pull request merged**
